Add error checking for non numeric TMDB ids
haijeploeg/excludarr pull request #46
Opened 2022-01-15 06:46 UTC by Tailslide

Fixes #44 so that program does not abort when ID's returned from TMDB have 'tt' on the start.
Example output:

```
BAD TMDB IDS: ['tt11388406']
BAD TMDB IDS: ['tt11388406']

              ╷                       ╷                ╷                        
 Release Date │ Title                 │ Used Diskspace │ Streaming Providers    
╶─────────────┼───────────────────────┼────────────────┼───────────────────────╴
 2022-01-05   │ Test Movie            │ 0.00GB         │ Netflix  
```

2022-01-15 09:45 UTC, haijeploeg requested changes
As `get_tmdb_ids` is a filter, it should not print anything and only return the valid values. I would prefer the following; This will add a check if the tmdb id is indeed numeric.

```
def get_tmdb_ids(external_ids):
    try:
        tmdb_ids = [
            int(x["external_id"])
            for x in external_ids
            if (x["provider"] == "tmdb_latest" or x["provider"] == "tmdb") and x["external_id"].isnumeric()
        ]
        tmdb_ids = list(set(tmdb_ids))
    except (KeyError, IndexError):
        tmdb_ids = []

    return tmdb_ids
```

2022-01-15 21:16 UTC, Tailslide commented
Ok I pasted in this change thanks for taking the time to look at this.

2022-01-16 09:55 UTC, haijeploeg approved these changes

2022-01-16 09:56 UTC, haijeploeg commented
Cool! I will create a release for it today :)

2022-01-16 09:56 UTC, merged